name: readme_preamble

on:
  push:
    paths:
      - "*/README.md"
      - "scripts/readme_preamble.*"
      - "justfile"
      - ".github/workflows/readme_preamble.yml"
  pull_request:
    paths:
      - "*/README.md"
      - "scripts/readme_preamble.*"
      - "justfile"
      - ".github/workflows/readme_preamble.yml"

jobs:
  check:
    name: Package README preambles
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0
      - run: just readme-preamble-check
